export const ADD_STORE = 'ADD_STORE';
export const FETCH_PRODUCTS_STARTED = 'FETCH_PRODUCTS_STARTED'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
