export const userTypes = {
  USER_SIGNUP_REQUESTING: 'USER_SIGNUP_REQUESTING',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',

  USER_LOGIN_REQUESTING: 'USER_LOGIN_REQUESTING',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE'
} 