export const requestLoan = {
  REQUEST_LOAN_REQUESTING: 'REQUEST_LOAN_REQUESTING',
  REQUEST_LOAN_SUCCESS: 'REQUEST_LOAN_SUCCESS',
  REQUEST_LOAN_FAILURE: 'REQUEST_LOAN_FAILURE',
  DELETE_REQUEST_LOAN: 'DELETE_REQUEST_LOAN'
} 