export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCTS_FETCH_LOADING = 'PRODUCTS_FETCH_LOADING';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_FAILURE = 'PRODUCTS_FETCH_FAILURE';